### ISSUE TITLE
Simplify top Makefile. Sometimes copy-paste and hard-coded values are better.

### ISSUE THREAD

**Issue by krisjans** [ShpakovDmitry/My-old-projects#11]
It is important to use Makefile variables and avoid copy-paste and I like that you take this seriously.
But those variables should make life easier (and this includes "code must be easy to read"). Sometimes a little of copy-paste makes code so much easier to understand.

https://github.com/ShpakovDmitry/My-old-projects/blob/409bd3c811549b08751c3e99cb4ace2906795120/embedded/EscapeROOM/Makefile#L1-L21
versus 
```
all:
 	make -C med_panel/ all 
 	make -C radio_morse_panel/ all
 	cp */build/*.hex .

clean:
 	make -C med_panel/ clean 
 	make -C radio_morse_panel/ clean
 	-rm *.hex
```
Even top level build directory is not quite necessary. Those hex files are the thing you want - maybe there is no need to hide them into sub-folder.
Another way of simplification is to omit hex file copying from sub-projects altogether.

**Comment by ShpakovDmitry** [comment]
Totally agree with you, that suggested listing is much easier to read.
