### ISSUE TITLE
EscapeROOM - Consider two sub-projects.  

### ISSUE THREAD

**Issue by krisjans** [ShpakovDmitry/My-old-projects#8]
https://github.com/ShpakovDmitry/My-old-projects/blob/8358996a7ce16021b013ebf5ea791a2c414f4860/embedded/EscapeROOM/README.md#L3

Is there anything in common for those two projects? It might be much easier to support two projects with single device each than single project with two devices.
If there is shared code you might want to bring it out into pseudo-lib:
```
EscapeROOM/README.md
EscapeROOM/Makefile // main makefile
EscapeROOM/morse_panel/ // independent sub-project
EscapeROOM/med_panel/ // independent sub-project
EscapeROOM/lib/ // shared code goes into this subfoldere
EscapeROOM/build/ // store hex files from all sub-projects 
```

**Comment by ShpakovDmitry** [comment]
Actually, the only thing that is common for those projects is that devices supposed to work
in one room close to each other. But there is no any interaction between devices.
In my opinion it should be better to keep those projects in common project forlder `EscapeROOM`,
but each in sub-project folder.
